ProyectoNet6BaseAdminLTE/Areas/Admin/Controllers/BodegaController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoNet6BaseAdminLTE.AccesoDatos.Repositorio.IRepositorio;

namespace ProyectoNet6BaseAdminLTE.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BodegaController : Controller
    {
        private readonly IUnidadTrabajo _unidadTrabajo;
        public BodegaController(IUnidadTrabajo unidadTrabajo)
        {
            _unidadTrabajo = unidadTrabajo;
        }
        public IActionResult Index()
        {
            return  View();
        }
        #region API
        [HttpGet]
        public async Task<IActionResult> ObtenerTodos()
        {
            var todos = await _unidadTrabajo.Bodega.ObtenerTodos();
            return Json(new { data = todos });
        }
        #endregion
    }
}

ProyectoNet6BaseAdminLTE/Areas/Inventario/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoNet6BaseAdminLTE.Modelos.ViewModels;
using System.Diagnostics;

namespace ProyectoNet6BaseAdminLTE.Areas.Inventario.Controllers
{
    [Area("Inventario")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProyectoNet6BaseAdminLTE/Areas/Admin/Views/Bodega/Index.cshtml
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Listado de Bodegas</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">                        
                    <li class="breadcrumb-item active">
                        <a class="btn btn-primary"><i class="fas fa-plus"></i> Agregar</a>
                    </li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
    
<div class="card">
    <div class="card-header">
    <h3 class="card-title">Simple Full Width Table</h3>

    <div class="card-tools">
        <ul class="pagination pagination-sm float-right">
        <li class="page-item"><a class="page-link" href="#">«</a></li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item"><a class="page-link" href="#">»</a></li>
        </ul>
    </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
    <table class="table">
        <thead>
        <tr>
            <th style="width: 10px">#</th>
            <th>Task</th>
            <th>Progress</th>
            <th style="width: 40px">Label</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>1.</td>
            <td>Update software</td>
            <td>
            <div class="progress progress-xs">
                <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
            </div>
            </td>
            <td><span class="badge bg-danger">55%</span></td>
        </tr>
        <tr>
            <td>2.</td>
            <td>Clean database</td>
            <td>
            <div class="progress progress-xs">
                <div class="progress-bar bg-warning" style="width: 70%"></div>
            </div>
            </td>
            <td><span class="badge bg-warning">70%</span></td>
        </tr>
        <tr>
            <td>3.</td>
            <td>Cron job running</td>
            <td>
            <div class="progress progress-xs progress-striped active">
                <div class="progress-bar bg-primary" style="width: 30%"></div>
            </div>
            </td>
            <td><span class="badge bg-primary">30%</span></td>
        </tr>
        <tr>
            <td>4.</td>
            <td>Fix and squish bugs</td>
            <td>
            <div class="progress progress-xs progress-striped active">
                <div class="progress-bar bg-success" style="width: 90%"></div>
            </div>
            </td>
            <td><span class="badge bg-success">90%</span></td>
        </tr>
        </tbody>
    </table>
    </div>
    <!-- /.card-body -->
</div>

@section Scripts{
    <script src="~/js/bodega.js"></script>
}

ProyectoNet6BaseAdminLTE/Areas/Inventario/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProyectoNet6BaseAdminLTE/Views/Shared/_ControlSidebar.cshtml
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->

ProyectoNet6BaseAdminLTE/Views/Shared/_Footer.cshtml
<!-- Main Footer -->
<footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 3.1.0
    </div>
</footer>

ProyectoNet6BaseAdminLTE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoNet6BaseAdminLTE</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/lib/AdminLTE-3.2.0/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/lib/AdminLTE-3.2.0/plugins/fontawesome-free/css/all.min.css">
    
    <!-- overlayScrollbars -->
    @*<link rel="stylesheet" href="~/lib/AdminLTE-3.2.0/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">*@
    <!-- DataTables -->
    <link rel="stylesheet" href="~/lib/AdminLTE-3.2.0/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/lib/AdminLTE-3.2.0/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/lib/AdminLTE-3.2.0/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/lib/AdminLTE-3.2.0/dist/css/adminlte.min.css">

</head>
<body class="hold-transition sidebar-mini layout-fixed sidebar-collapse">
    <div class="wrapper">
        <partial name="_Preloader" />
        <partial name="_Navbar" />
        <partial name="_MainSidebar" />
        <div class="content-wrapper" style="min-height: 600px;">
            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                        @RenderBody()
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <partial name="_ControlSidebar" />
        <partial name="_Footer" />
    </div>
    <!-- jQuery -->
    <script src="~/lib/AdminLTE-3.2.0/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    @*<script src="~/lib/AdminLTE-3.2.0/plugins/jquery-ui/jquery-ui.min.js"></script>*@
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    @*<script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>*@
    <!-- Bootstrap 4 -->
    <script src="~/lib/AdminLTE-3.2.0/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    @*<script src="~/lib/AdminLTE-3.2.0/plugins/chart.js/Chart.min.js"></script>*@
    <!-- Sparkline -->
    <!--<script src="~/lib/AdminLTE-3.2.0/plugins/sparklines/sparkline.js"></script>-->
    <!-- JQVMap -->
    @*<script src="~/lib/AdminLTE-3.2.0/plugins/jqvmap/jquery.vmap.min.js"></script>
        <script src="~/lib/AdminLTE-3.2.0/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>*@
    <!-- jQuery Knob Chart -->
    @*<script src="~/lib/AdminLTE-3.2.0/plugins/jquery-knob/jquery.knob.min.js"></script>*@
    <!-- daterangepicker -->
    <script src="~/lib/AdminLTE-3.2.0/plugins/moment/moment.min.js"></script>
    <script src="~/lib/AdminLTE-3.2.0/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    @*<script src="~/lib/AdminLTE-3.2.0/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>*@
    <!-- Bootstrap Toogle -->
    <link href="~/lib/AdminLTE-3.2.0/plugins/bootstraptoggle/css/bootstrap-toggle.min.css" rel="stylesheet">
    <script src="~/lib/AdminLTE-3.2.0/plugins/bootstraptoggle/js/bootstrap-toggle.min.js"></script>
    <!-- Summernote -->
    @*<script src="~/lib/AdminLTE-3.2.0/plugins/summernote/summernote-bs4.min.js"></script>*@
    <!-- overlayScrollbars -->
    @*<script src="~/lib/AdminLTE-3.2.0/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>*@
    <!-- AdminLTE App -->
    <script src="~/lib/AdminLTE-3.2.0/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    @*    <script src="~/lib/AdminLTE-3.2.0/dist/js/demo.js"></script>
    *@    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    @*<script src="~/lib/AdminLTE-3.2.0/dist/js/pages/dashboard2.js"></script>*@  @*Datos de prueba para el dashboard 2*@

    <!-- DataTables  & Plugins -->
    <script src="~/lib/AdminLTE-3.2.0/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/lib/AdminLTE-3.2.0/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/lib/AdminLTE-3.2.0/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/lib/AdminLTE-3.2.0/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/lib/AdminLTE-3.2.0/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/lib/AdminLTE-3.2.0/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    @*<script src="~/lib/AdminLTE-3.2.0/plugins/jszip/jszip.min.js"></script>
    <script src="~/lib/AdminLTE-3.2.0/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/lib/AdminLTE-3.2.0/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/lib/AdminLTE-3.2.0/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/lib/AdminLTE-3.2.0/plugins/datatables-buttons/js/buttons.print.min.js"></script>*@
    <script src="~/lib/AdminLTE-3.2.0/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    <script src="~/lib/AdminLTE-3.2.0/plugins/datatables/sum().js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProyectoNet6BaseAdminLTE/Views/Shared/_Navbar.cshtml
  <!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a  asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a asp-area="Admin" asp-controller="Bodega" asp-action="Index" class="nav-link">Bodega</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">U: @Environment.UserName</a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="~/lib/AdminLTE-3.2.0/dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Brad Diesel
                                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">Call me whenever you can...</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="~/lib/AdminLTE-3.2.0/dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                John Pierce
                                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">I got your message bro</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="~/lib/AdminLTE-3.2.0/dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Nora Silvester
                                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">The subject goes here</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li>
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>
</nav>
<!-- /.navbar -->

ProyectoNet6BaseAdminLTE/Views/Shared/_Preloader.cshtml
<!-- Preloader -->
<div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__wobble" src="~/lib/AdminLTE-3.2.0/dist/img/loading_layout.gif" alt="AdminLTELogo" width="120">
</div>